name: cptests

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup cptests
        uses: actions/checkout@v3

      - name: Set
        run: npm update --registry=https://registry.npmjs.org/
        
      - name: Run eslint
        run: npm run lint

      - name: Run Test with tags
        run: npx cypress run --env tags='@Login'
    
      - name: Run tests chromium
        env:
          BROWSER: chromium
        run: npx cypress run --browser chrome
      
      - name: Upload test coverage as artifact for chromium
        uses: actions/upload-artifact@v3
        with:
          name: chromium-report
          path: cucumber-report.html
          retention-days: 5
          
      - name: Run tests firefox
        env:
          BROWSER: firefox
        run: npx cypress run --browser firefox
      
      - name: Upload test coverage as artifact for firefox
        uses: actions/upload-artifact@v3
        with:
          name: firefox-report
          path: cucumber-report.html
          retention-days: 5
